Repository grpc/grpc-swift-extras, pull requests merged in 2024-10, with the labels that each got.

#4 Fix naming
  Sources/GRPCHealthService/Generated/health.grpc.swift
  Sources/GRPCHealthService/HealthService.swift
  Sources/GRPCInterceptors/ClientTracingInterceptor.swift
  Sources/GRPCInterceptors/ServerTracingInterceptor.swift
  Sources/GRPCInteropTests/Generated/empty_service.grpc.swift
  Sources/GRPCInteropTests/Generated/test.grpc.swift
  Sources/GRPCInteropTests/InteroperabilityTestCases.swift
  Sources/GRPCInteropTests/TestService.swift
  Tests/GRPCHealthServiceTests/HealthTests.swift
  Tests/GRPCInterceptorsTests/TracingInterceptorTests.swift
  Tests/InProcessInteropTests/InProcessInteroperabilityTests.swift
Labels: semver/patch

#5 Set grpc-swift version to 2.0.0-alpha.1
  Package.swift
Labels: semver/patch

#7 Add deployment targets to the package manifest
  Package.swift
  Sources/GRPCHealthService/Health.swift
  Sources/GRPCHealthService/HealthService.swift
  Sources/GRPCInterceptors/ClientTracingInterceptor.swift
  Sources/GRPCInterceptors/HookedWriter.swift
  Sources/GRPCInterceptors/OnFinishAsyncSequence.swift
  Sources/GRPCInterceptors/ServerTracingInterceptor.swift
  Sources/GRPCInteropTests/InteroperabilityTestCase.swift
  Sources/GRPCInteropTests/InteroperabilityTestCases.swift
  Sources/GRPCInteropTests/TestService.swift
  Sources/GRPCReflectionService/Server/ReflectionService.swift
  Sources/GRPCReflectionService/Server/ReflectionServiceV1.swift
  Sources/GRPCReflectionService/Server/ReflectionServiceV1Alpha.swift
  Sources/GRPCReflectionService/v1/reflection-v1.grpc.swift
  Sources/GRPCReflectionService/v1Alpha/reflection-v1alpha.grpc.swift
  Tests/GRPCHealthServiceTests/HealthTests.swift
  Tests/GRPCInterceptorsTests/TracingInterceptorTests.swift
  Tests/GRPCInterceptorsTests/TracingTestsUtilities.swift
  Tests/InProcessInteropTests/InProcessInteroperabilityTests.swift
Labels: ⚠️ semver/major

#6 Add README and .spi.yml
  .spi.yml
  CONTRIBUTING.md
  NOTICES.txt
  README.md
  SECURITY.md
  Sources/GRPCHealthService/Documentation.docc/Documentation.md
Labels: semver/none

#8 Depend on `grpc-swift/main`
  Package.swift
  Tests/GRPCInterceptorsTests/TracingInterceptorTests.swift
Labels: semver/none
