Repository grpc/grpc-swift-extras, pull requests merged in 2024-12, with the labels that each got.

#13 Update generated code
  Sources/GRPCHealthService/Generated/health.grpc.swift
  Sources/GRPCHealthService/HealthService.swift
  Sources/GRPCInteropTests/Generated/empty_service.grpc.swift
  Sources/GRPCInteropTests/Generated/test.grpc.swift
  Tests/GRPCHealthServiceTests/HealthTests.swift
  Tests/GRPCInterceptorsTests/TracingInterceptorTests.swift
Labels: semver/patch

#14 Update generated code
  Sources/GRPCHealthService/Generated/health.grpc.swift
  Sources/GRPCInteropTests/Generated/empty_service.grpc.swift
  Sources/GRPCInteropTests/Generated/test.grpc.swift
Labels: semver/patch

#15 Bump dependency version
  Package.swift
Labels: semver/patch

#16 Enable MemberImportVisibility check on all targets
  Package.swift
  Sources/GRPCInteropTests/InteroperabilityTestCases.swift
  Sources/GRPCInteropTests/TestService.swift
  Tests/GRPCHealthServiceTests/HealthTests.swift
Labels: semver/patch

#17 Use FoundationEssentials where possible
  Sources/GRPCInteropTests/InteroperabilityTestCases.swift
  Sources/GRPCInteropTests/TestService.swift
Labels: semver/minor

#19 Remove unused grpc-swift v1 reflection code
  Sources/GRPCReflectionService/Documentation.docc/ReflectionServiceTutorial.md
  Sources/GRPCReflectionService/Server/ReflectionService.swift
  Sources/GRPCReflectionService/Server/ReflectionServiceV1.swift
  Sources/GRPCReflectionService/Server/ReflectionServiceV1Alpha.swift
  Sources/GRPCReflectionService/v1/reflection-v1.grpc.swift
  Sources/GRPCReflectionService/v1/reflection-v1.pb.swift
  Sources/GRPCReflectionService/v1Alpha/reflection-v1alpha.grpc.swift
  Sources/GRPCReflectionService/v1Alpha/reflection-v1alpha.pb.swift
Labels: semver/none

#20 Update fetch and generate scripts for reflection
  .licenseignore
  Sources/GRPCReflectionService/Generated/reflection.grpc.swift
  Sources/GRPCReflectionService/Generated/reflection.pb.swift
  Tests/GRPCReflectionServiceTests/Generated/DescriptorSets/base_message.pb
  Tests/GRPCReflectionServiceTests/Generated/DescriptorSets/health.pb
  Tests/GRPCReflectionServiceTests/Generated/DescriptorSets/message_with_dependency.pb
  Tests/GRPCReflectionServiceTests/Generated/DescriptorSets/reflection.pb
  dev/protos/fetch.sh
  dev/protos/generate.sh
  dev/protos/tests/reflection/base_message.proto
  dev/protos/tests/reflection/message_with_dependency.proto
  dev/protos/upstream/grpc/reflection/v1/reflection.proto
Labels: semver/none

#21 Add support for the reflection service
  Package.swift
  Sources/GRPCReflectionService/Service/ReflectionService+V1.swift
  Sources/GRPCReflectionService/Service/ReflectionService.swift
  Sources/GRPCReflectionService/Service/ReflectionServiceRegistry.swift
  Tests/GRPCReflectionServiceTests/GRPCReflectionServiceTests.swift
  Tests/GRPCReflectionServiceTests/ReflectionClient.swift
Labels: 🆕 semver/minor

#22 Bump versions
  Package.swift
Labels: 🔨 semver/patch

#23 Add missing test import
  Tests/GRPCReflectionServiceTests/GRPCReflectionServiceTests.swift
Labels: semver/none
