Repository grpc/grpc-swift-extras, pull requests merged in 2025-01, with the labels that each got.

#26 Regenerate and update dependencies
  Package.swift
  Sources/GRPCHealthService/Generated/health.grpc.swift
  Sources/GRPCHealthService/HealthService.swift
  Sources/GRPCInteropTests/Generated/empty.grpc.swift
  Sources/GRPCInteropTests/Generated/empty_service.grpc.swift
  Sources/GRPCInteropTests/Generated/messages.grpc.swift
  Sources/GRPCInteropTests/Generated/test.grpc.swift
  Sources/GRPCInteropTests/InteroperabilityTestCase.swift
  Sources/GRPCInteropTests/InteroperabilityTestCases.swift
  Sources/GRPCReflectionService/Generated/reflection.grpc.swift
  Sources/GRPCReflectionService/Service/ReflectionService.swift
  Tests/GRPCHealthServiceTests/HealthTests.swift
  Tests/GRPCInterceptorsTests/TracingInterceptorTests.swift
  Tests/GRPCReflectionServiceTests/ReflectionClient.swift
Labels: 🔨 semver/patch

#28 Depend on beta 3 tag
  Package.swift
Labels: semver/none

#29 Add `GRPCServiceLifecycle` module
  Package.swift
  Sources/GRPCServiceLifecycle/GRPCClient+Service.swift
  Sources/GRPCServiceLifecycle/GRPCServer+Service.swift
  Tests/GRPCServiceLifecycleTests/ServiceLifecycleConformanceTests.swift
  Tests/InProcessInteropTests/InProcessInteroperabilityTests.swift
Labels: 🆕 semver/minor

#25 Conform client's tracing interceptor to OTel's conventions
  Package.swift
  Sources/GRPCInterceptors/ClientTracingInterceptor.swift
  Sources/GRPCInterceptors/HookedAsyncSequence.swift
  Sources/GRPCInterceptors/HookedWriter.swift
  Sources/GRPCInterceptors/OnFinishAsyncSequence.swift
  Sources/GRPCInterceptors/Tracing/ClientOTelTracingInterceptor.swift
  Sources/GRPCInterceptors/Tracing/ServerTracingInterceptor.swift
  Sources/GRPCInterceptors/Tracing/SpanAttributes+GRPCTracingKeys.swift
  Tests/GRPCInterceptorsTests/PeerAddressTests.swift
  Tests/GRPCInterceptorsTests/TracingInterceptorTests.swift
  Tests/GRPCInterceptorsTests/TracingTestsUtilities.swift
  dev/license-check.sh
Labels: ⚠️ semver/major

#27 Conform server tracing interceptor to OTel's conventions
  Sources/GRPCInterceptors/Tracing/ClientOTelTracingInterceptor.swift
  Sources/GRPCInterceptors/Tracing/ServerOTelTracingInterceptor.swift
  Sources/GRPCInterceptors/Tracing/SpanAttributes+GRPCTracingKeys.swift
  Tests/GRPCInterceptorsTests/OTelTracingInterceptorTests.swift
  Tests/GRPCInterceptorsTests/TracingTestsUtilities.swift
Labels: ⚠️ semver/major

#31 Rename interceptors module
  .spi.yml
  Package.swift
  Sources/GRPCOTelTracingInterceptors/HookedAsyncSequence.swift
  Sources/GRPCOTelTracingInterceptors/HookedWriter.swift
  Sources/GRPCOTelTracingInterceptors/Tracing/ClientOTelTracingInterceptor.swift
  Sources/GRPCOTelTracingInterceptors/Tracing/ServerOTelTracingInterceptor.swift
  Sources/GRPCOTelTracingInterceptors/Tracing/SpanAttributes+GRPCTracingKeys.swift
  Tests/GRPCOTelTracingInterceptorsTests/GRPCOTelTracingInterceptorsTests.swift
  Tests/GRPCOTelTracingInterceptorsTests/PeerAddressTests.swift
  Tests/GRPCOTelTracingInterceptorsTests/TracingTestsUtilities.swift
Labels: ⚠️ semver/major

#32 Add missing documentation bundles
  .spi.yml
  Sources/GRPCInteropTests/Documentation.docc/Documentation.md
  Sources/GRPCOTelTracingInterceptors/Documentation.docc/Documentation.md
  Sources/GRPCReflectionService/Documentation.docc/Documentation.md
  Sources/GRPCServiceLifecycle/Documentation.docc/Documentation.md
Labels: semver/none

#33 Bump dependency versions
  Package.swift
Labels: 🔨 semver/patch

#36 Relax dependency requirements
  Package.swift
Labels: 🔨 semver/patch
